name: "Group 1 Workflow"
on:
  workflow_dispatch:
jobs:
  
  run_python:
    name: "Run Group 1"
    uses: ./.github/workflows/template.yaml
    with:
      GHA_ENVIRONMENT: wayne-group1
    secrets:
      SECRET: ${{ secrets.SECRET }}

