name: "Group 2 Workflow" 
on:
  workflow_dispatch:
jobs:

  run_python:
    name: "Run Group 2"
    uses: ./.github/workflows/template.yaml
    with:
      GHA_ENVIRONMENT: wayne-group2
    secrets:
      SECRET: ${{ secrets.SECRET }}

