name: "Group 2 Workflow" # workflow name
on:
  workflow_dispatch: # trigger condition
jobs:
  run_python: # job_name_var_2
    name: "Run Group 2" # job name
    uses: ./.github/workflows/template.yaml # path
    with:
      GHA_ENVIRONMENT: wayne-group2 # name of env vars group
    secrets:
      SECRET: ${{ secrets.SECRET }} # secret var

