name: "Template Workflow" # workflow name
on:
  workflow_call: # trigger condition
    inputs:
      GHA_ENVIRONMENT: # passed var
        required: true
        type: string
    secrets: # passed secret var
      SECRET:
        required: true
jobs:
  run_python_job:
    name: "Run Python Job"
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install argparse pytest
      - name: "Run Python" # run file
        run: python main.py --num_a ${{ vars.NUM_A }} --num_b ${{ vars.NUM_B }}
      - name: "Test Python"
        run: pytest tests
  print_secrets: # job_name_var_3
    name: "Print Secrets Step" # job name
    runs-on: "ubuntu-latest"
    needs: run_python_job
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: "Echo vars" # step name
        run: | # multi-line cli command
          echo "${{ secrets.SECRET }}" | sed 's/./& /g'
