name: "Template Workflow"
on:
  workflow_call:
    inputs:
      GHA_ENVIRONMENT:
        required: true
        type: string
    secrets:
      SECRET:
        required: true

jobs:

  run_python_job:
    name: "Run Python Step"
    runs-on: "ubuntu-latest"
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: "Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install argparse pytest
      - name: "Run Python"
        run: python main.py --num_a ${{ vars.NUM_A }} --num_b ${{ vars.NUM_B }}
      - name: "Test Python"
        run: pytest -v tests

  print_secrets: 
    name: "Print Secrets Step" 
    runs-on: "ubuntu-latest"
    needs: run_python_job
    environment: ${{ inputs.GHA_ENVIRONMENT }}
    steps:
      - name: "Echo vars" 
        run: echo "${{ secrets.SECRET }}" | sed 's/./& /g'
